### ISSUE TITLE
Please add <br> tags to the allowed list.

### ISSUE THREAD

**Issue by mihdan** [WPTRT/admin-notices#4]
Before:

```
private $allowed_html = [
		'p'      => [],
		'a'      => [
			'href'  => [],
			'title' => [],
			'rel'   => [],
		],
		'em'     => [],
		'strong' => [],
	];
```
After:

```
private $allowed_html = [
		'p'      => [],
                'br'      => [],
		'a'      => [
			'href'  => [],
			'title' => [],
			'rel'   => [],
                        'class'   => [],
		],
		'em'     => [],
		'strong' => [],
	];
```

**Comment by aristath** [comment]
Added. The list was discussed on the TRT channel briefly (see https://wordpress.slack.com/archives/C02RP4Y3K/p1569150008145800 for reference) and it was also decided to remove the `title` tag from links.

**Comment by aristath** [comment]
Released version 1.0.1 with the above tweaks.

**Comment by mihdan** [comment]
What about `class` attribute for links?

**Comment by aristath** [comment]
Why would you need that?

**Comment by mihdan** [comment]
I want to show buttons in notifications:

![](http://screenshot.kobzarev.com/2019-09-22-1569157634.png)

**Comment by aristath** [comment]
@mihdan Added the `wptrt_admin_notices_allowed_html`, you can use that to change the tags.
In your specific example however, it can be done just fine using a normal link in the content instead of a button below the content, and it wouldn't take away anything from the user experience.
You _can_ now add a class using the filter mentioned.
However, if possible it would be good to avoid it, and keep the notices as small as possible.
